### ISSUE TITLE
Is there any way to check if model has some kind of vertex attribute?

### ISSUE THREAD

**Issue by peloct** [UkooLabs/FBXSharpie#1]
Hello!

I found this awesome project today, So I just tried it.

(Actually, I am looking for simple fbx loader for my graphics study, and it is perfect for me. Thank you for your work! :+1: )

But when I try to load my fbx file and call "FbxDocument.GetTangents" method, NullReference exception has occurred.

I think it was because my 3d model doesn't have any tangent attributes.

Well.. I finally added some null check code like below.

~~~cs
if (documentNode.GetRelative("LayerElementTangent/Tangents") == null)
{
}
~~~

It works good, but I guess it is a little bit cumbersome.

Is there any way to check if model has some kind of vertex attribute more easy way?

Thank you for watching.

**Comment by UkooLabs** [comment]
Hi,

Wow that’s quick only just put it live today :)
I do have a bit of refactoring to do and feedback is very welcome. I’m open to any ideas but maybe I should add a has tangent property and also return empty array if it gets called.

I’ll keep you posted once I update probably tomorrow if I find time.

Peter

**Comment by UkooLabs** [comment]
@peloct just committed an update, have a look and let me know your thoughts

**Comment by peloct** [comment]
Hello!

Just before, I tried to load my model with "UkooLabs.FbxSharpie v1.0.117".

And It worked well!

I can load all my models without checking if it has a specific vertex attributes.

I think it is more convenient to have a empty list as a result of querying(what you did), than always checking if it is null, and actually it is more intuitive.

Thank you for your fast feedback.

**Comment by UkooLabs** [comment]
@peloct glad working well, My main next focus is trying to fix FBX binary writing so started to create tests to identify where things are going wrong. Let me know if you have any other feature requests.
