### ISSUE TITLE
Support multiple layers/sets for vertex attributes.

### ISSUE THREAD

**Issue by KillzXGaming** [UkooLabs/FBXSharpie#8]
![Capture](https://user-images.githubusercontent.com/13475262/73138138-5e6b0780-402d-11ea-996a-921f440903c9.PNG)

Example of an FBX with multiple UV layers. I would allow an option to search for the index of the layer element.

**Comment by UkooLabs** [comment]
@KillzXGaming do you have a full fbx example file I can use as will help me implement + test properly

**Comment by KillzXGaming** [comment]
Here

[PlaneMultiUVs.zip](https://github.com/UkooLabs/FBXSharpie/files/4137134/PlaneMultiUVs.zip)

**Comment by UkooLabs** [comment]
@KillzXGaming thank you

**Comment by UkooLabs** [comment]
@KillzXGaming finally got round to implementing among other bug fixes, updated readme with simple example
